//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the Pegasus Asset Compiler.
//     Wednesday, 15 January 2014, 18:34:16
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using Pegasus;
using Pegasus.Math;
using Pegasus.Platform;
using Pegasus.Platform.Assets;
using Pegasus.Platform.Graphics;
using Pegasus.Platform.Memory;

namespace Lwar.Assets.Effects
{
	/// <summary>
	///     Applies a Gaussian blur filter to a texture.
	/// </summary>
	public sealed class BlurEffect : Effect
	{
		/// <summary>
		///     Initializes a new instance.
		/// </summary>
		/// <param name="graphicsDevice">The graphics device this instance belongs to.</param>
		/// <param name="assets">The assets manager that should be used to load required assets.</param>
		public BlurEffect(GraphicsDevice graphicsDevice, AssetsManager assets)
			: base(graphicsDevice, assets)
		{
			Gaussian = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/BlurEffect.VertexShader.1", 
				"Effects/BlurEffect.GaussianBlur.1");
		}

		/// <summary>
		///     The texture that is blurred.
		/// </summary>
		public Texture2DView Texture { get; set; }

		/// <summary>
		///     Applies a single-pass Gaussian blur filter.
		/// </summary>
		public EffectTechnique Gaussian { get; private set; }

		/// <summary>
		///     Binds all textures and non-shared constant buffers required by the effect.
		/// </summary>
		private void __Bind()
		{
			__context.Bind(Texture, 0);
		}

		/// <summary>
		///     Unbinds all textures required by the effect.
		/// </summary>
		private void __Unbind()
		{
			__context.Unbind(Texture, 0);
		}
	}
}

namespace Lwar.Assets.Effects
{
	public sealed class ParallaxEffect : Effect
	{
		/// <summary>
		///     Initializes a new instance.
		/// </summary>
		/// <param name="graphicsDevice">The graphics device this instance belongs to.</param>
		/// <param name="assets">The assets manager that should be used to load required assets.</param>
		public ParallaxEffect(GraphicsDevice graphicsDevice, AssetsManager assets)
			: base(graphicsDevice, assets)
		{
			Default = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/ParallaxEffect.VertexShader.1", 
				"Effects/ParallaxEffect.FragmentShader.1");
		}

		public Texture2DView TextureAtlas { get; set; }

		public EffectTechnique Default { get; private set; }

		/// <summary>
		///     Binds all textures and non-shared constant buffers required by the effect.
		/// </summary>
		private void __Bind()
		{
			__context.Bind(TextureAtlas, 0);
		}

		/// <summary>
		///     Unbinds all textures required by the effect.
		/// </summary>
		private void __Unbind()
		{
			__context.Unbind(TextureAtlas, 0);
		}
	}
}

namespace Lwar.Assets.Effects
{
	public sealed class SkyboxEffect : Effect
	{
		/// <summary>
		///     Initializes a new instance.
		/// </summary>
		/// <param name="graphicsDevice">The graphics device this instance belongs to.</param>
		/// <param name="assets">The assets manager that should be used to load required assets.</param>
		public SkyboxEffect(GraphicsDevice graphicsDevice, AssetsManager assets)
			: base(graphicsDevice, assets)
		{
			Default = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/SkyboxEffect.VertexShader.1", 
				"Effects/SkyboxEffect.FragmentShader.1");
		}

		public CubeMapView Skybox { get; set; }

		public EffectTechnique Default { get; private set; }

		/// <summary>
		///     Binds all textures and non-shared constant buffers required by the effect.
		/// </summary>
		private void __Bind()
		{
			__context.Bind(Skybox, 0);
		}

		/// <summary>
		///     Unbinds all textures required by the effect.
		/// </summary>
		private void __Unbind()
		{
			__context.Unbind(Skybox, 0);
		}
	}
}

namespace Lwar.Assets.Effects
{
	public sealed class SphereEffect : Effect
	{
		/// <summary>
		///     Indicates whether the contents of ShieldConstantBuffer have changed.
		/// </summary>
		private bool __ShieldConstantBufferDirty = true;

		/// <summary>
		///     Indicates whether the contents of PlanetConstantBuffer have changed.
		/// </summary>
		private bool __PlanetConstantBufferDirty = true;

		/// <summary>
		///     Indicates whether the contents of ConstantBuffer4 have changed.
		/// </summary>
		private bool __ConstantBuffer4Dirty = true;

		/// <summary>
		///     Passes the shader constants in the ShieldConstantBuffer constant buffer to the GPU.
		/// </summary>
		private readonly ConstantBuffer _ShieldConstantBuffer;

		/// <summary>
		///     Passes the shader constants in the PlanetConstantBuffer constant buffer to the GPU.
		/// </summary>
		private readonly ConstantBuffer _PlanetConstantBuffer;

		/// <summary>
		///     Passes the shader constants in the ConstantBuffer4 constant buffer to the GPU.
		/// </summary>
		private readonly ConstantBuffer _ConstantBuffer4;

		private Vector3 _ImpactPosition;

		private float _TimeToLive;

		private Vector3 _SunPosition;

		private Matrix _World;

		/// <summary>
		///     Initializes a new instance.
		/// </summary>
		/// <param name="graphicsDevice">The graphics device this instance belongs to.</param>
		/// <param name="assets">The assets manager that should be used to load required assets.</param>
		public unsafe SphereEffect(GraphicsDevice graphicsDevice, AssetsManager assets)
			: base(graphicsDevice, assets)
		{
			Default = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/SphereEffect.VertexShader.1", 
				"Effects/SphereEffect.FragmentShader.1");
			Planet = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/SphereEffect.VertexShaderPlanet.1", 
				"Effects/SphereEffect.FragmentShaderPlanet.1");
			Shield = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/SphereEffect.VertexShaderShield.1", 
				"Effects/SphereEffect.FragmentShaderShield.1");

			_ShieldConstantBuffer = __context.CreateConstantBuffer(__ShieldConstantBuffer.Size, __ShieldConstantBuffer.Slot);
			_ShieldConstantBuffer.SetName("used by Lwar.Assets.Effects.SphereEffect");

			_PlanetConstantBuffer = __context.CreateConstantBuffer(__PlanetConstantBuffer.Size, __PlanetConstantBuffer.Slot);
			_PlanetConstantBuffer.SetName("used by Lwar.Assets.Effects.SphereEffect");

			_ConstantBuffer4 = __context.CreateConstantBuffer(__ConstantBuffer4.Size, __ConstantBuffer4.Slot);
			_ConstantBuffer4.SetName("used by Lwar.Assets.Effects.SphereEffect");
		}

		public Vector3 ImpactPosition
		{
			get { return _ImpactPosition; }
			set
			{
				_ImpactPosition = value;
				__ShieldConstantBufferDirty = true;
			}
		}

		public float TimeToLive
		{
			get { return _TimeToLive; }
			set
			{
				_TimeToLive = value;
				__ShieldConstantBufferDirty = true;
			}
		}

		public Vector3 SunPosition
		{
			get { return _SunPosition; }
			set
			{
				_SunPosition = value;
				__PlanetConstantBufferDirty = true;
			}
		}

		public Matrix World
		{
			get { return _World; }
			set
			{
				_World = value;
				__ConstantBuffer4Dirty = true;
			}
		}

		public CubeMapView SphereTexture { get; set; }

		public EffectTechnique Default { get; private set; }

		public EffectTechnique Planet { get; private set; }

		public EffectTechnique Shield { get; private set; }

		/// <summary>
		///     Binds all textures and non-shared constant buffers required by the effect.
		/// </summary>
		private unsafe void __Bind()
		{
			if (__ShieldConstantBufferDirty)
			{
				var __data = new __ShieldConstantBuffer();
				__data.ImpactPosition = ImpactPosition;
				__data.TimeToLive = TimeToLive;

				__ShieldConstantBufferDirty = false;
				__context.Update(_ShieldConstantBuffer, &__data);
			}

			if (__PlanetConstantBufferDirty)
			{
				var __data = new __PlanetConstantBuffer();
				__data.SunPosition = SunPosition;

				__PlanetConstantBufferDirty = false;
				__context.Update(_PlanetConstantBuffer, &__data);
			}

			if (__ConstantBuffer4Dirty)
			{
				var __data = new __ConstantBuffer4();
				__data.World = World;

				__ConstantBuffer4Dirty = false;
				__context.Update(_ConstantBuffer4, &__data);
			}

			__context.Bind(SphereTexture, 0);
			__context.Bind(_ShieldConstantBuffer);
			__context.Bind(_PlanetConstantBuffer);
			__context.Bind(_ConstantBuffer4);
		}

		/// <summary>
		///     Unbinds all textures required by the effect.
		/// </summary>
		private void __Unbind()
		{
			__context.Unbind(SphereTexture, 0);
		}

		/// <summary>
		///     Disposes the object, releasing all managed and unmanaged resources.
		/// </summary>
		protected override void __OnDisposing()
		{
			_ShieldConstantBuffer.SafeDispose();
			_PlanetConstantBuffer.SafeDispose();
			_ConstantBuffer4.SafeDispose();
		}

		[StructLayout(LayoutKind.Explicit, Size = Size)]
		private struct __ShieldConstantBuffer
		{
			/// <summary>
			///     The size of the struct in bytes.
			/// </summary>
			public const int Size = 16;

			/// <summary>
			///     The slot the constant buffer is assigned to.
			/// </summary>
			public const int Slot = 2;

			[FieldOffset(0)]
			public Vector3 ImpactPosition;

			[FieldOffset(12)]
			public float TimeToLive;
		}

		[StructLayout(LayoutKind.Explicit, Size = Size)]
		private struct __PlanetConstantBuffer
		{
			/// <summary>
			///     The size of the struct in bytes.
			/// </summary>
			public const int Size = 16;

			/// <summary>
			///     The slot the constant buffer is assigned to.
			/// </summary>
			public const int Slot = 3;

			[FieldOffset(0)]
			public Vector3 SunPosition;
		}

		[StructLayout(LayoutKind.Explicit, Size = Size)]
		private struct __ConstantBuffer4
		{
			/// <summary>
			///     The size of the struct in bytes.
			/// </summary>
			public const int Size = 64;

			/// <summary>
			///     The slot the constant buffer is assigned to.
			/// </summary>
			public const int Slot = 4;

			[FieldOffset(0)]
			public Matrix World;
		}
	}
}

namespace Lwar.Assets.Effects
{
	public sealed class SpriteEffect : Effect
	{
		/// <summary>
		///     Indicates whether the contents of ConstantBuffer2 have changed.
		/// </summary>
		private bool __ConstantBuffer2Dirty = true;

		/// <summary>
		///     Passes the shader constants in the ConstantBuffer2 constant buffer to the GPU.
		/// </summary>
		private readonly ConstantBuffer _ConstantBuffer2;

		private Matrix _World;

		/// <summary>
		///     Initializes a new instance.
		/// </summary>
		/// <param name="graphicsDevice">The graphics device this instance belongs to.</param>
		/// <param name="assets">The assets manager that should be used to load required assets.</param>
		public unsafe SpriteEffect(GraphicsDevice graphicsDevice, AssetsManager assets)
			: base(graphicsDevice, assets)
		{
			Default = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/SpriteEffect.VertexShader.1", 
				"Effects/SpriteEffect.FragmentShader.1");

			_ConstantBuffer2 = __context.CreateConstantBuffer(__ConstantBuffer2.Size, __ConstantBuffer2.Slot);
			_ConstantBuffer2.SetName("used by Lwar.Assets.Effects.SpriteEffect");
		}

		public Matrix World
		{
			get { return _World; }
			set
			{
				_World = value;
				__ConstantBuffer2Dirty = true;
			}
		}

		public Texture2DView Sprite { get; set; }

		public EffectTechnique Default { get; private set; }

		/// <summary>
		///     Binds all textures and non-shared constant buffers required by the effect.
		/// </summary>
		private unsafe void __Bind()
		{
			if (__ConstantBuffer2Dirty)
			{
				var __data = new __ConstantBuffer2();
				__data.World = World;

				__ConstantBuffer2Dirty = false;
				__context.Update(_ConstantBuffer2, &__data);
			}

			__context.Bind(Sprite, 0);
			__context.Bind(_ConstantBuffer2);
		}

		/// <summary>
		///     Unbinds all textures required by the effect.
		/// </summary>
		private void __Unbind()
		{
			__context.Unbind(Sprite, 0);
		}

		/// <summary>
		///     Disposes the object, releasing all managed and unmanaged resources.
		/// </summary>
		protected override void __OnDisposing()
		{
			_ConstantBuffer2.SafeDispose();
		}

		[StructLayout(LayoutKind.Explicit, Size = Size)]
		private struct __ConstantBuffer2
		{
			/// <summary>
			///     The size of the struct in bytes.
			/// </summary>
			public const int Size = 64;

			/// <summary>
			///     The slot the constant buffer is assigned to.
			/// </summary>
			public const int Slot = 2;

			[FieldOffset(0)]
			public Matrix World;
		}
	}
}

namespace Lwar.Assets.Effects
{
	public sealed class SunEffect : Effect
	{
		/// <summary>
		///     Indicates whether the contents of ConstantBuffer2 have changed.
		/// </summary>
		private bool __ConstantBuffer2Dirty = true;

		/// <summary>
		///     Passes the shader constants in the ConstantBuffer2 constant buffer to the GPU.
		/// </summary>
		private readonly ConstantBuffer _ConstantBuffer2;

		private Matrix _Rotation1;

		private Matrix _Rotation2;

		private Matrix _World;

		/// <summary>
		///     Initializes a new instance.
		/// </summary>
		/// <param name="graphicsDevice">The graphics device this instance belongs to.</param>
		/// <param name="assets">The assets manager that should be used to load required assets.</param>
		public unsafe SunEffect(GraphicsDevice graphicsDevice, AssetsManager assets)
			: base(graphicsDevice, assets)
		{
			Default = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/SunEffect.VertexShader.1", 
				"Effects/SunEffect.FragmentShader.1");

			_ConstantBuffer2 = __context.CreateConstantBuffer(__ConstantBuffer2.Size, __ConstantBuffer2.Slot);
			_ConstantBuffer2.SetName("used by Lwar.Assets.Effects.SunEffect");
		}

		public Matrix Rotation1
		{
			get { return _Rotation1; }
			set
			{
				_Rotation1 = value;
				__ConstantBuffer2Dirty = true;
			}
		}

		public Matrix Rotation2
		{
			get { return _Rotation2; }
			set
			{
				_Rotation2 = value;
				__ConstantBuffer2Dirty = true;
			}
		}

		public Matrix World
		{
			get { return _World; }
			set
			{
				_World = value;
				__ConstantBuffer2Dirty = true;
			}
		}

		public CubeMapView CubeMap { get; set; }
		public Texture2DView HeatMap { get; set; }

		public EffectTechnique Default { get; private set; }

		/// <summary>
		///     Binds all textures and non-shared constant buffers required by the effect.
		/// </summary>
		private unsafe void __Bind()
		{
			if (__ConstantBuffer2Dirty)
			{
				var __data = new __ConstantBuffer2();
				__data.Rotation1 = Rotation1;
				__data.Rotation2 = Rotation2;
				__data.World = World;

				__ConstantBuffer2Dirty = false;
				__context.Update(_ConstantBuffer2, &__data);
			}

			__context.Bind(CubeMap, 0);
			__context.Bind(HeatMap, 1);
			__context.Bind(_ConstantBuffer2);
		}

		/// <summary>
		///     Unbinds all textures required by the effect.
		/// </summary>
		private void __Unbind()
		{
			__context.Unbind(CubeMap, 0);
			__context.Unbind(HeatMap, 1);
		}

		/// <summary>
		///     Disposes the object, releasing all managed and unmanaged resources.
		/// </summary>
		protected override void __OnDisposing()
		{
			_ConstantBuffer2.SafeDispose();
		}

		[StructLayout(LayoutKind.Explicit, Size = Size)]
		private struct __ConstantBuffer2
		{
			/// <summary>
			///     The size of the struct in bytes.
			/// </summary>
			public const int Size = 192;

			/// <summary>
			///     The slot the constant buffer is assigned to.
			/// </summary>
			public const int Slot = 2;

			[FieldOffset(0)]
			public Matrix Rotation1;

			[FieldOffset(64)]
			public Matrix Rotation2;

			[FieldOffset(128)]
			public Matrix World;
		}
	}
}

namespace Lwar.Assets.Effects
{
	public sealed class TexturedQuadEffect : Effect
	{
		/// <summary>
		///     Indicates whether the contents of ConstantBuffer2 have changed.
		/// </summary>
		private bool __ConstantBuffer2Dirty = true;

		/// <summary>
		///     Passes the shader constants in the ConstantBuffer2 constant buffer to the GPU.
		/// </summary>
		private readonly ConstantBuffer _ConstantBuffer2;

		private Vector4 _Color;

		private Matrix _World;

		/// <summary>
		///     Initializes a new instance.
		/// </summary>
		/// <param name="graphicsDevice">The graphics device this instance belongs to.</param>
		/// <param name="assets">The assets manager that should be used to load required assets.</param>
		public unsafe TexturedQuadEffect(GraphicsDevice graphicsDevice, AssetsManager assets)
			: base(graphicsDevice, assets)
		{
			ColoredTexturedQuad = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/TexturedQuadEffect.VertexShader.1", 
				"Effects/TexturedQuadEffect.ColoredTexturedQuadFragmentShader.1");
			FullScreen = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/TexturedQuadEffect.FullScreenVertexShader.1", 
				"Effects/TexturedQuadEffect.TexturedQuadFragmentShader.1");
			TexturedQuad = __context.CreateTechnique(__Bind, __Unbind,
				"Effects/TexturedQuadEffect.VertexShader.1", 
				"Effects/TexturedQuadEffect.TexturedQuadFragmentShader.1");

			_ConstantBuffer2 = __context.CreateConstantBuffer(__ConstantBuffer2.Size, __ConstantBuffer2.Slot);
			_ConstantBuffer2.SetName("used by Lwar.Assets.Effects.TexturedQuadEffect");
		}

		public Vector4 Color
		{
			get { return _Color; }
			set
			{
				_Color = value;
				__ConstantBuffer2Dirty = true;
			}
		}

		public Matrix World
		{
			get { return _World; }
			set
			{
				_World = value;
				__ConstantBuffer2Dirty = true;
			}
		}

		public Texture2DView Texture { get; set; }

		public EffectTechnique ColoredTexturedQuad { get; private set; }

		public EffectTechnique FullScreen { get; private set; }

		public EffectTechnique TexturedQuad { get; private set; }

		/// <summary>
		///     Binds all textures and non-shared constant buffers required by the effect.
		/// </summary>
		private unsafe void __Bind()
		{
			if (__ConstantBuffer2Dirty)
			{
				var __data = new __ConstantBuffer2();
				__data.Color = Color;
				__data.World = World;

				__ConstantBuffer2Dirty = false;
				__context.Update(_ConstantBuffer2, &__data);
			}

			__context.Bind(Texture, 0);
			__context.Bind(_ConstantBuffer2);
		}

		/// <summary>
		///     Unbinds all textures required by the effect.
		/// </summary>
		private void __Unbind()
		{
			__context.Unbind(Texture, 0);
		}

		/// <summary>
		///     Disposes the object, releasing all managed and unmanaged resources.
		/// </summary>
		protected override void __OnDisposing()
		{
			_ConstantBuffer2.SafeDispose();
		}

		[StructLayout(LayoutKind.Explicit, Size = Size)]
		private struct __ConstantBuffer2
		{
			/// <summary>
			///     The size of the struct in bytes.
			/// </summary>
			public const int Size = 80;

			/// <summary>
			///     The slot the constant buffer is assigned to.
			/// </summary>
			public const int Slot = 2;

			[FieldOffset(0)]
			public Vector4 Color;

			[FieldOffset(16)]
			public Matrix World;
		}
	}
}

