//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the Pegasus Asset Compiler.
//     Thursday, 10 October 2013, 20:23:54
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Pegasus.Platform.Graphics;
using Pegasus.Framework;
using Pegasus.Framework.UserInterface;
using Pegasus.Framework.UserInterface.Controls;

namespace Lwar.UserInterface
{
	public partial class UserControl2 : UserControl
	{
		public UserControl2()
		{
			var canvas1 = new Canvas();
			this.Content = canvas1;
		}
	}
}


// <Create Type="Pegasus.Framework.UserInterface.Controls.UserControl, pegasus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:d="http://schemas.microsoft.com/expression/blend/2008" Name="this">
//   <Set Property="Content">
//     <Value Type="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
//       <Create Type="Pegasus.Framework.UserInterface.Controls.Canvas, pegasus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" Name="canvas1" />
//     </Value>
//   </Set>
// </Create>
