//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the Pegasus Asset Compiler.
//     Wednesday, 18 December 2013, 17:40:44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Framework.UserInterface.Controls
{
	using System;
	using Pegasus.Platform.Graphics;
	using Pegasus.Framework;
	using Pegasus.Framework.UserInterface;
	using Pegasus.Framework.UserInterface.Controls;

	public partial class AppWindow : Pegasus.Framework.UserInterface.Controls.Window
	{
		private Pegasus.Framework.UserInterface.Controls.RenderOutputPanel RenderOutputPanel;

		/// <summary>
		///     Initializes a new instance.
		/// </summary>
		public AppWindow()
		{
			InitializeComponents();
		}

		/// <summary>
		///     Initializes the UI element's children.
		/// </summary>
		private void InitializeComponents()
		{
			this.FontFamily = "Liberation Mono";
			this.FontSize = 11;
			Pegasus.Framework.UserInterface.TextOptions.SetTextRenderingMode(this, TextRenderingMode.Aliased);
			this.Background = Color.FromRgba(0, 0, 0, 255);
			this.Title = "lwar";
			this.Height = 506.85;
			this.Width = 871;
			RenderOutputPanel = new Pegasus.Framework.UserInterface.Controls.RenderOutputPanel();
			this.Child = RenderOutputPanel;
		}
	}
}

