//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the Pegasus Asset Compiler.
//     Friday, April 5, 2013, 8:32:08
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Pegasus.Framework.Scripting
{

	public class CvarRegistry : Registry<ICvar>
	{
		/// <summary>
		///   The name of the player that identifies the player in networked games.
		/// </summary>
		private readonly Cvar<string> _playerName = new Cvar<string>("player_name", "UnnamedPlayer", "The name of the player that identifies the player in networked games.", true);

		/// <summary>
		///   The scaling factor that is applied to all timing values.
		/// </summary>
		private readonly Cvar<double> _timeScale = new Cvar<double>("time_scale", 1.0, "The scaling factor that is applied to all timing values.", false);

		/// <summary>
		///   Initializes a new instance.
		/// </summary>
		public CvarRegistry()
		{
			Register(_playerName, "player_name");
			Register(_timeScale, "time_scale");
		}

		/// <summary>
		///   The name of the player that identifies the player in networked games.
		/// </summary>
		public string PlayerName
		{
			get { return _playerName.Value; }
			set { _playerName.Value = value; }
		}

		/// <summary>
		///   The scaling factor that is applied to all timing values.
		/// </summary>
		public double TimeScale
		{
			get { return _timeScale.Value; }
			set { _timeScale.Value = value; }
		}
	}
}

