//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the Pegasus Asset Compiler.
//     Thursday, 10 October 2013, 18:56:20
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Pegasus.Platform.Graphics;
using Pegasus.Framework;
using Pegasus.Framework.UserInterface;
using Pegasus.Framework.UserInterface.Controls;

namespace Lwar
{
	public partial class LwarApplication : Application
	{
		public LwarApplication()
		{
		}
	}
}


// <Create Type="Pegasus.Framework.Application, pegasus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" Name="this" />
