using System;

namespace Lwar
{
	using System.Runtime.CompilerServices;
	using Gameplay.Entities;
	using Pegasus.Framework.Rendering.UserInterface;

	// base interface for all view model interfaces
	internal interface IViewModel
	{
		event Action<object, string> PropertyChanged;
	}

	internal interface IObservableList<T>
	{
	}

	// defined in assets project
	internal interface IScoreboardViewModel : IViewModel
	{
		/// <summary>
		///   Rank of the local player
		/// </summary>
		int Rank { get; }

		IObservableList<IPlayerInfo> PlayerInfo { get; }
	}

	internal interface IPlayerInfo : IViewModel
	{
		int Deaths { get; }
		int Kills { get; }
		int Ping { get; }
		string Name { get; }
	}

	// Viewmodel base class
	internal class ViewModel : IViewModel
	{
		public event Action<object, string> PropertyChanged;

		protected void NotifyPropertyChanged([CallerMemberName] String propertyName = "")
		{
			if (PropertyChanged != null)
			{
				PropertyChanged(this, propertyName);
			}
		}
	}

	// Generated by asset compiler
	internal partial class ScoreboardViewModel : ViewModel, IScoreboardViewModel
	{
		private IObservableList<IPlayerInfo> _playerInfos;
		private int _rank;

		/// <summary>
		///   Rank of the local player
		/// </summary>
		public int Rank
		{
			get { return _rank; }
			set
			{
				if (_rank == value)
					return;

				_rank = value;
				NotifyPropertyChanged();
				OnRankChanged(value, value);
			}
		}

		partial void OnRankChanged(int oldValue, int newValue);

		public IObservableList<IPlayerInfo> PlayerInfo
		{
			get { return _playerInfos; }
			set
			{
				if (_playerInfos == value)
					return;

				_playerInfos = value;
				NotifyPropertyChanged();
				OnPlayerInfoChanged(value, value);
			}
		}

		partial void OnPlayerInfoChanged(IObservableList<IPlayerInfo> oldValue, IObservableList<IPlayerInfo> newValue);
	}

	// Generated by asset compiler
	internal class ScoreboardView : Control
	{
		public ScoreboardView(IScoreboardViewModel viewModel)
		{
			DataContext = viewModel;

			var list = new ItemsSource();
			list.ItemsTemplate = new Template()
			{
				Content = new StackPanel()
				{
					new Label
					{
						Text = new Binding
						{
							SourceValue = s => ((IPlayerInfo)s).Kills
						}
					}
				}
			};
			list.Items = new Binding()// source expression: must be able to cope with dep props/regular props, etc.
			{
				// source expr must react to all changes in the property path
				// GetSourceValue, SetSourceValue, GetTargetValue,SetTargetValue
				SourceValue = () => 
					{
						var dataContext = DependencyObject.GetValue(FrameworkElement.DataContextProperty, this);
						return ((IScoreboardViewModel)dataContext).PlayerInfo;
					}

			};

			Content = list;
		}
	}

	// Viewmodel written by user
	partial class ScoreboardViewModel
	{
		partial void OnRankChanged(int oldValue, int newValue)
		{
			
		}
	}
}