//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the Pegasus Asset Compiler.
//     Wednesday, 21 August 2013, 10:29:15
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lwar.Gameplay.Entities
{
	using Assets;
	using Pegasus;
	using Pegasus.Platform;
	using Pegasus.Platform.Assets;
	using Pegasus.Platform.Graphics;
	using Pegasus.Platform.Memory;
	using Pegasus.Rendering;

	public static class EntityTemplates
	{
		public static EntityTemplate Bullet { get; private set; }
		public static EntityTemplate Earth { get; private set; }
		public static EntityTemplate Gun { get; private set; }
		public static EntityTemplate Jupiter { get; private set; }
		public static EntityTemplate Mars { get; private set; }
		public static EntityTemplate Moon { get; private set; }
		public static EntityTemplate Phaser { get; private set; }
		public static EntityTemplate Ray { get; private set; }
		public static EntityTemplate Rocket { get; private set; }
		public static EntityTemplate Ship { get; private set; }
		public static EntityTemplate Shockwave { get; private set; }
		public static EntityTemplate Sun { get; private set; }

		public static void Initialize(GraphicsDevice graphicsDevice, AssetsManager assets)
		{
			Assert.ArgumentNotNull(graphicsDevice);
			Assert.ArgumentNotNull(assets);

			Bullet = new EntityTemplate
			(
				maxEnergy: 0.0f,
				maxHealth: 2000.0f,
				radius: 16.0f,
				texture: null,
				cubeMap: null,
				model: null
			);

			Earth = new EntityTemplate
			(
				maxEnergy: 0.0f,
				maxHealth: 1.0f,
				radius: 256.0f,
				texture: null,
				cubeMap: assets.LoadCubeMap(Textures.EarthCubemap),
				model: Model.CreateSphere(graphicsDevice, 256, 16)
			);

			Gun = new EntityTemplate
			(
				maxEnergy: 1000.0f,
				maxHealth: 1.0f,
				radius: 0.0f,
				texture: null,
				cubeMap: null,
				model: null
			);

			Jupiter = new EntityTemplate
			(
				maxEnergy: 0.0f,
				maxHealth: 1.0f,
				radius: 512.0f,
				texture: null,
				cubeMap: assets.LoadCubeMap(Textures.JupiterCubemap),
				model: Model.CreateSphere(graphicsDevice, 512, 16)
			);

			Mars = new EntityTemplate
			(
				maxEnergy: 0.0f,
				maxHealth: 1.0f,
				radius: 128.0f,
				texture: null,
				cubeMap: assets.LoadCubeMap(Textures.MarsCubemap),
				model: Model.CreateSphere(graphicsDevice, 128, 16)
			);

			Moon = new EntityTemplate
			(
				maxEnergy: 0.0f,
				maxHealth: 1.0f,
				radius: 64.0f,
				texture: null,
				cubeMap: assets.LoadCubeMap(Textures.MoonCubemap),
				model: Model.CreateSphere(graphicsDevice, 64, 16)
			);

			Phaser = new EntityTemplate
			(
				maxEnergy: 1000.0f,
				maxHealth: 1.0f,
				radius: 0.0f,
				texture: null,
				cubeMap: null,
				model: null
			);

			Ray = new EntityTemplate
			(
				maxEnergy: 1.0f,
				maxHealth: 1.0f,
				radius: 4096.0f,
				texture: null,
				cubeMap: null,
				model: null
			);

			Rocket = new EntityTemplate
			(
				maxEnergy: 1000.0f,
				maxHealth: 1.0f,
				radius: 16.0f,
				texture: null,
				cubeMap: null,
				model: null
			);

			Ship = new EntityTemplate
			(
				maxEnergy: 1000.0f,
				maxHealth: 3000.0f,
				radius: 64.0f,
				texture: null,
				cubeMap: null,
				model: null
			);

			Shockwave = new EntityTemplate
			(
				maxEnergy: 0.0f,
				maxHealth: 0.0f,
				radius: 0.0f,
				texture: null,
				cubeMap: null,
				model: null
			);

			Sun = new EntityTemplate
			(
				maxEnergy: 0.0f,
				maxHealth: 1.0f,
				radius: 1500.0f,
				texture: null,
				cubeMap: null,
				model: null
			);
		}

		public static void Dispose()
		{
			Bullet.SafeDispose();
			Earth.SafeDispose();
			Gun.SafeDispose();
			Jupiter.SafeDispose();
			Mars.SafeDispose();
			Moon.SafeDispose();
			Phaser.SafeDispose();
			Ray.SafeDispose();
			Rocket.SafeDispose();
			Ship.SafeDispose();
			Shockwave.SafeDispose();
			Sun.SafeDispose();
		}
	}
}
