//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EntityTemplates.fsx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lwar.Client.Gameplay.Entities
{
    public enum EntityType
    {
        Bullet = 1, 
        Ship = 2, 
        Planet = 3, 
        Rocket = 4, 
        Gun = 5, 
        Phaser = 6, 
        Sun = 7, 
        Ray = 8, 
        Shockwave = 9, 
        Jupiter = 10, 
        Moon = 11, 
        Mars = 12, 
    }
}
