//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EntityTemplates.fsx.
//     Wednesday, 12 June 2013, 12:56:29
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lwar.Client.Gameplay.Entities
{
    using Pegasus.Framework;
    using Pegasus.Framework.Platform;
    using Pegasus.Framework.Platform.Graphics;
    using Pegasus.Framework.Platform.Memory;
    using Pegasus.Framework.Rendering;

    public static class Templates
    {
        public static Template Bullet { get; private set; }
        public static Template Gun { get; private set; }
        public static Template Phaser { get; private set; }
        public static Template Planet { get; private set; }
        public static Template Mars { get; private set; }
        public static Template Moon { get; private set; }
        public static Template Jupiter { get; private set; }
        public static Template Sun { get; private set; }
        public static Template Ray { get; private set; }
        public static Template Rocket { get; private set; }
        public static Template Ship { get; private set; }

        public static void Initialize(GraphicsDevice graphicsDevice, AssetsManager assets)
        {
            Assert.ArgumentNotNull(graphicsDevice);
            Assert.ArgumentNotNull(assets);

            Bullet = new Template
            (
                maxEnergy: 0.0f,
                maxHealth: 2000.0f,
                radius: 16.0f,
                texture: null,
                cubeMap: null,
                model: null
            );

            Gun = new Template
            (
                maxEnergy: 1000.0f,
                maxHealth: 1.0f,
                radius: 0.0f,
                texture: null,
                cubeMap: null,
                model: null
            );

            Phaser = new Template
            (
                maxEnergy: 1000.0f,
                maxHealth: 1.0f,
                radius: 0.0f,
                texture: null,
                cubeMap: null,
                model: null
            );

            Planet = new Template
            (
                maxEnergy: 0.0f,
                maxHealth: 1.0f,
                radius: 256.0f,
                texture: null,
                cubeMap: assets.LoadCubeMap("Textures/Planet"),
                model: Model.CreateSphere(graphicsDevice, 256, 32)
            );

            Mars = new Template
            (
                maxEnergy: 0.0f,
                maxHealth: 1.0f,
                radius: 128.0f,
                texture: null,
                cubeMap: assets.LoadCubeMap("Textures/Mars"),
                model: Model.CreateSphere(graphicsDevice, 128, 16)
            );

            Moon = new Template
            (
                maxEnergy: 0.0f,
                maxHealth: 1.0f,
                radius: 64.0f,
                texture: null,
                cubeMap: assets.LoadCubeMap("Textures/Moon"),
                model: Model.CreateSphere(graphicsDevice, 64, 8)
            );

            Jupiter = new Template
            (
                maxEnergy: 0.0f,
                maxHealth: 1.0f,
                radius: 512.0f,
                texture: null,
                cubeMap: assets.LoadCubeMap("Textures/Jupiter"),
                model: Model.CreateSphere(graphicsDevice, 512, 64)
            );

            Sun = new Template
            (
                maxEnergy: 0.0f,
                maxHealth: 1.0f,
                radius: 1500.0f,
                texture: null,
                cubeMap: null,
                model: null
            );

            Ray = new Template
            (
                maxEnergy: 0.0f,
                maxHealth: 1.0f,
                radius: 2048.0f,
                texture: null,
                cubeMap: null,
                model: null
            );

            Rocket = new Template
            (
                maxEnergy: 1000.0f,
                maxHealth: 1.0f,
                radius: 16.0f,
                texture: null,
                cubeMap: null,
                model: null
            );

            Ship = new Template
            (
                maxEnergy: 1000.0f,
                maxHealth: 10000.0f,
                radius: 64.0f,
                texture: null,
                cubeMap: null,
                model: null
            );

        }

        public static void Dispose()
        {
            Bullet.SafeDispose();
            Gun.SafeDispose();
            Phaser.SafeDispose();
            Planet.SafeDispose();
            Mars.SafeDispose();
            Moon.SafeDispose();
            Jupiter.SafeDispose();
            Sun.SafeDispose();
            Ray.SafeDispose();
            Rocket.SafeDispose();
            Ship.SafeDispose();
        }
    }
}
