//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EntityTemplates.fsx.
//     Tuesday, 11 June 2013, 09:14:30
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lwar.Client.Gameplay.Entities
{
    public partial class Bullet
    {
        /// <summary>
        ///   The entity's maximum energy level.
        /// </summary>
        public const float MaxEnergy = 0.0f;

        /// <summary>
        ///   The entity's maximum health.
        /// </summary>
        public const float MaxHealth = 100.0f;

        /// <summary>
        ///   The entity's radius, defining its size.
        /// </summary>
        public const float Radius = 16.0f;
    }

    public partial class Gun
    {
        /// <summary>
        ///   The entity's maximum energy level.
        /// </summary>
        public const float MaxEnergy = 1000.0f;

        /// <summary>
        ///   The entity's maximum health.
        /// </summary>
        public const float MaxHealth = 1.0f;

        /// <summary>
        ///   The entity's radius, defining its size.
        /// </summary>
        public const float Radius = 0.0f;
    }

    public partial class Phaser
    {
        /// <summary>
        ///   The entity's maximum energy level.
        /// </summary>
        public const float MaxEnergy = 1000.0f;

        /// <summary>
        ///   The entity's maximum health.
        /// </summary>
        public const float MaxHealth = 1.0f;

        /// <summary>
        ///   The entity's radius, defining its size.
        /// </summary>
        public const float Radius = 0.0f;
    }

    public partial class Planet
    {
        /// <summary>
        ///   The entity's maximum energy level.
        /// </summary>
        public const float MaxEnergy = 0.0f;

        /// <summary>
        ///   The entity's maximum health.
        /// </summary>
        public const float MaxHealth = 1.0f;

        /// <summary>
        ///   The entity's radius, defining its size.
        /// </summary>
        public const float Radius = 128.0f;
    }

    public partial class Sun
    {
        /// <summary>
        ///   The entity's maximum energy level.
        /// </summary>
        public const float MaxEnergy = 0.0f;

        /// <summary>
        ///   The entity's maximum health.
        /// </summary>
        public const float MaxHealth = 1.0f;

        /// <summary>
        ///   The entity's radius, defining its size.
        /// </summary>
        public const float Radius = 512.0f;
    }

    public partial class Ray
    {
        /// <summary>
        ///   The entity's maximum energy level.
        /// </summary>
        public const float MaxEnergy = 0.0f;

        /// <summary>
        ///   The entity's maximum health.
        /// </summary>
        public const float MaxHealth = 1.0f;

        /// <summary>
        ///   The entity's radius, defining its size.
        /// </summary>
        public const float Radius = 2048.0f;
    }

    public partial class Rocket
    {
        /// <summary>
        ///   The entity's maximum energy level.
        /// </summary>
        public const float MaxEnergy = 1000.0f;

        /// <summary>
        ///   The entity's maximum health.
        /// </summary>
        public const float MaxHealth = 1.0f;

        /// <summary>
        ///   The entity's radius, defining its size.
        /// </summary>
        public const float Radius = 16.0f;
    }

    public partial class Ship
    {
        /// <summary>
        ///   The entity's maximum energy level.
        /// </summary>
        public const float MaxEnergy = 1000.0f;

        /// <summary>
        ///   The entity's maximum health.
        /// </summary>
        public const float MaxHealth = 200.0f;

        /// <summary>
        ///   The entity's radius, defining its size.
        /// </summary>
        public const float Radius = 64.0f;
    }

}
