//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EntityTemplates.fsx.
//     Monday, 15 April 2013, 15:57:35
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lwar.Client.Gameplay
{
    public enum EntityType
    {
        Bullet = 1, 
        Ship = 2, 
        Planet = 3, 
        Rocket = 4, 
        Gun = 5, 
        Phaser = 6, 
        Sun = 7, 
        Ray = 8, 
        Shockwave = 9, 
    }
}
