//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the Pegasus Asset Compiler.
//     Wednesday, 15 January 2014, 18:34:28
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Pegasus.Platform.Assets;

namespace Lwar.Assets
{
	public static class Textures
	{
		public static AssetIdentifier<Pegasus.Platform.Graphics.CubeMap> JupiterCubemap = "Textures/Jupiter.Cubemap.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.CubeMap> MarsCubemap = "Textures/Mars.Cubemap.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.CubeMap> MoonCubemap = "Textures/Moon.Cubemap.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.CubeMap> EarthCubemap = "Textures/Earth.Cubemap.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.CubeMap> ShieldsCubemap = "Textures/Shields.Cubemap.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.CubeMap> SpaceCubemap = "Textures/Space.Cubemap.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.CubeMap> SunCubemap = "Textures/Sun.Cubemap.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.CubeMap> SunHeatCubemap = "Textures/SunHeat.Cubemap.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> Bullet = "Textures/Bullet.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> BulletGlow = "Textures/BulletGlow.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> Explosion = "Textures/Explosion.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> Heat = "Textures/Heat.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> Parallax = "Textures/Parallax.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> Phaser = "Textures/Phaser.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> PhaserGlow = "Textures/PhaserGlow.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> Rocket = "Textures/Rocket.1";
		public static AssetIdentifier<Pegasus.Platform.Graphics.Texture2D> Ship = "Textures/Ship.1";
	}

	public static class Fonts
	{
		public static AssetIdentifier<Pegasus.Rendering.UserInterface.Font> LiberationMono11 = "Fonts/Liberation Mono 11.1";
	}
}
