using System;

namespace Pegasus.Framework.Platform.Graphics
{
	/// <summary>
	///   Indicates whether and how a texture uses mipmaps.
	/// </summary>
	public enum Mipmaps
	{
		/// <summary>
		///   Indicates that the texture supports automatic mipmap generation.
		/// </summary>
		AutoGenerated = -1,

		/// <summary>
		///   Indicates that the texture does not use any mipmaps.
		/// </summary>
		None = 0,

		/// <summary>
		///   Indicates that one mipmap is provided by the application.
		/// </summary>
		One = 1,

		/// <summary>
		///   Indicates that two mipmaps are provided by the application.
		/// </summary>
		Two = 2,

		/// <summary>
		///   Indicates that three mipmaps are provided by the application.
		/// </summary>
		Three = 3,

		/// <summary>
		///   Indicates that four mipmaps are provided by the application.
		/// </summary>
		Four = 4,

		/// <summary>
		///   Indicates that five mipmaps are provided by the application.
		/// </summary>
		Five = 5,

		/// <summary>
		///   Indicates that six mipmaps are provided by the application.
		/// </summary>
		Six = 6,

		/// <summary>
		///   Indicates that seven mipmaps are provided by the application.
		/// </summary>
		Seven = 7,

		/// <summary>
		///   Indicates that eight mipmaps are provided by the application.
		/// </summary>
		Eight = 8,

		/// <summary>
		///   Indicates that nine mipmaps are provided by the application.
		/// </summary>
		Nine = 9,

		/// <summary>
		///   Indicates that ten mipmaps are provided by the application.
		/// </summary>
		Ten = 10,

		/// <summary>
		///   Indicates that eleven mipmaps are provided by the application.
		/// </summary>
		Eleven = 11,

		/// <summary>
		///   Indicates that twelve mipmaps are provided by the application.
		/// </summary>
		Twelve = 12,

		/// <summary>
		///   Indicates that thirteen mipmaps are provided by the application.
		/// </summary>
		Thirteen = 13,

		/// <summary>
		///   Indicates that fourteen mipmaps are provided by the application.
		/// </summary>
		Fourteen = 14,

		/// <summary>
		///   Indicates that fifteen mipmaps are provided by the application.
		/// </summary>
		Fifteen = 15,
	}
}