//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EntityTemplates.fsx.
// </auto-generated>
//------------------------------------------------------------------------------

enum
{
    ENTITY_TYPE_BULLET = 1, 
    ENTITY_TYPE_SHIP = 2, 
    ENTITY_TYPE_PLANET = 3, 
    ENTITY_TYPE_ROCKET = 4, 
    ENTITY_TYPE_GUN = 5, 
    ENTITY_TYPE_PHASER = 6, 
    ENTITY_TYPE_SUN = 7, 
    ENTITY_TYPE_RAY = 8, 
    ENTITY_TYPE_SHOCKWAVE = 9, 
    ENTITY_TYPE_JUPITER = 10, 
    ENTITY_TYPE_MOON = 11, 
    ENTITY_TYPE_MARS = 12, 
};
