//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EntityTemplates.fsx.
//     Tuesday, 16 April 2013, 16:02:49
// </auto-generated>
//------------------------------------------------------------------------------

enum
{
    ENTITY_TYPE_BULLET = 1, 
    ENTITY_TYPE_SHIP = 2, 
    ENTITY_TYPE_PLANET = 3, 
    ENTITY_TYPE_ROCKET = 4, 
    ENTITY_TYPE_GUN = 5, 
    ENTITY_TYPE_PHASER = 6, 
    ENTITY_TYPE_SUN = 7, 
    ENTITY_TYPE_RAY = 8, 
    ENTITY_TYPE_SHOCKWAVE = 9, 
};
