//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EntityTemplates.fsx.
//     Monday, 10 June 2013, 15:26:17
// </auto-generated>
//------------------------------------------------------------------------------

#include <math.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>

#include "server.h"
#include "rules.h"
#include "vector.h"

void decay(Entity *self);
void gun_shoot(Entity *self);
void phaser_shoot(Entity *self);
void gravity(Entity *self);
void gravity(Entity *self);
void ray_act(Entity *self);
void aim(Entity *self);

EntityType type_bullet =
{
    ENTITY_TYPE_BULLET, 
    decay, 
    NULL, 
    0, 
    0.0, 
    100.0, 
    0.0, 
    0.1, 
    16.0, 
    { 0.0, 1000.0 }, 
    { 0.0, 0.0 }, 
    0.0, 
};

EntityType type_gun =
{
    ENTITY_TYPE_GUN, 
    gun_shoot, 
    NULL, 
    300, 
    1000.0, 
    1.0, 
    0.0, 
    0.0, 
    0.0, 
    { 0.0, 0.0 }, 
    { 0.0, 0.0 }, 
    0.0, 
};

EntityType type_phaser =
{
    ENTITY_TYPE_PHASER, 
    phaser_shoot, 
    NULL, 
    0, 
    1000.0, 
    1.0, 
    0.0, 
    0.0, 
    0.0, 
    { 0.0, 0.0 }, 
    { 0.0, 0.0 }, 
    0.0, 
};

EntityType type_planet =
{
    ENTITY_TYPE_PLANET, 
    gravity, 
    NULL, 
    0, 
    0.0, 
    1.0, 
    0.0, 
    10000.0, 
    128.0, 
    { 0.0, 0.0 }, 
    { 0.0, 0.0 }, 
    0.0, 
};

EntityType type_sun =
{
    ENTITY_TYPE_SUN, 
    gravity, 
    NULL, 
    0, 
    0.0, 
    1.0, 
    0.0, 
    10000.0, 
    512.0, 
    { 0.0, 0.0 }, 
    { 0.0, 0.0 }, 
    0.0, 
};

EntityType type_ray =
{
    ENTITY_TYPE_RAY, 
    ray_act, 
    NULL, 
    0, 
    0.0, 
    1.0, 
    0.0, 
    0.0, 
    2048.0, 
    { 0.0, 0.0 }, 
    { 0.0, 0.0 }, 
    0.0, 
};

EntityType type_rocket =
{
    ENTITY_TYPE_ROCKET, 
    aim, 
    NULL, 
    0, 
    1000.0, 
    1.0, 
    0.0, 
    1.0, 
    16.0, 
    { 500.0, 20.0 }, 
    { 20.0, 20.0 }, 
    1.0, 
};

EntityType type_ship =
{
    ENTITY_TYPE_SHIP, 
    NULL, 
    NULL, 
    0, 
    1000.0, 
    200.0, 
    0.0, 
    1.0, 
    64.0, 
    { 500.0, 500.0 }, 
    { 500.0, 500.0 }, 
    3.0, 
};

