//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by EntityTemplates.fsx.
//     Tuesday, 11 June 2013, 19:28:40
// </auto-generated>
//------------------------------------------------------------------------------

#include <math.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>

#include "server.h"
#include "rules.h"
#include "vector.h"

void decay(Entity *self);
void gun_shoot(Entity *self);
void phaser_shoot(Entity *self);
void gravity(Entity *self);
void gravity(Entity *self);
void ray_act(Entity *self);
void aim(Entity *self);
void take_hit(Entity *self, Entity *other, Real impact);

EntityType type_bullet =
{
    // entity type
    ENTITY_TYPE_BULLET, 
    // action
    decay, 
    // collide
    NULL, 
    // interval
    0, 
    // energy
    0.0, 
    // health
    100.0, 
    // length
    0.0, 
    // mass
    0.1, 
    // radius
    16.0, 
    // acceleration
    { 0.0, 1200.0 }, 
    // deceleration
    { 0.0, 0.0 }, 
    // rotation
    0.0, 
};

EntityType type_gun =
{
    // entity type
    ENTITY_TYPE_GUN, 
    // action
    gun_shoot, 
    // collide
    NULL, 
    // interval
    300, 
    // energy
    1000.0, 
    // health
    1.0, 
    // length
    0.0, 
    // mass
    0.0, 
    // radius
    0.0, 
    // acceleration
    { 0.0, 0.0 }, 
    // deceleration
    { 0.0, 0.0 }, 
    // rotation
    0.0, 
};

EntityType type_phaser =
{
    // entity type
    ENTITY_TYPE_PHASER, 
    // action
    phaser_shoot, 
    // collide
    NULL, 
    // interval
    0, 
    // energy
    1000.0, 
    // health
    1.0, 
    // length
    0.0, 
    // mass
    0.0, 
    // radius
    0.0, 
    // acceleration
    { 0.0, 0.0 }, 
    // deceleration
    { 0.0, 0.0 }, 
    // rotation
    0.0, 
};

EntityType type_planet =
{
    // entity type
    ENTITY_TYPE_PLANET, 
    // action
    gravity, 
    // collide
    NULL, 
    // interval
    0, 
    // energy
    0.0, 
    // health
    1.0, 
    // length
    0.0, 
    // mass
    10000.0, 
    // radius
    128.0, 
    // acceleration
    { 0.0, 0.0 }, 
    // deceleration
    { 0.0, 0.0 }, 
    // rotation
    0.0, 
};

EntityType type_sun =
{
    // entity type
    ENTITY_TYPE_SUN, 
    // action
    gravity, 
    // collide
    NULL, 
    // interval
    0, 
    // energy
    0.0, 
    // health
    1.0, 
    // length
    0.0, 
    // mass
    10000.0, 
    // radius
    512.0, 
    // acceleration
    { 0.0, 0.0 }, 
    // deceleration
    { 0.0, 0.0 }, 
    // rotation
    0.0, 
};

EntityType type_ray =
{
    // entity type
    ENTITY_TYPE_RAY, 
    // action
    ray_act, 
    // collide
    NULL, 
    // interval
    0, 
    // energy
    0.0, 
    // health
    1.0, 
    // length
    0.0, 
    // mass
    0.0, 
    // radius
    2048.0, 
    // acceleration
    { 0.0, 0.0 }, 
    // deceleration
    { 0.0, 0.0 }, 
    // rotation
    0.0, 
};

EntityType type_rocket =
{
    // entity type
    ENTITY_TYPE_ROCKET, 
    // action
    aim, 
    // collide
    NULL, 
    // interval
    0, 
    // energy
    1000.0, 
    // health
    1.0, 
    // length
    0.0, 
    // mass
    1.0, 
    // radius
    16.0, 
    // acceleration
    { 500.0, 20.0 }, 
    // deceleration
    { 20.0, 20.0 }, 
    // rotation
    1.0, 
};

EntityType type_ship =
{
    // entity type
    ENTITY_TYPE_SHIP, 
    // action
    NULL, 
    // collide
    take_hit, 
    // interval
    0, 
    // energy
    1000.0, 
    // health
    200.0, 
    // length
    0.0, 
    // mass
    1.0, 
    // radius
    64.0, 
    // acceleration
    { 500.0, 500.0 }, 
    // deceleration
    { 500.0, 500.0 }, 
    // rotation
    3.0, 
};

