//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the Pegasus Asset Compiler.
//     Tuesday, 18 June 2013, 14:18:23
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#include <math.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>

#include "server.h"
#include "rules.h"
#include "vector.h"

void decay(Entity *self);
void gravity(Entity *self);
void gun_shoot(Entity *self);
void phaser_shoot(Entity *self);
void ray_act(Entity *self);
void aim(Entity *self);

void bullet_hit(Entity *self, Entity *other, Real impact);
void planet_hit(Entity *self, Entity *other, Real impact);
void ship_hit(Entity *self, Entity *other, Real impact);

EntityType type_bullet =
{
	ENTITY_TYPE_BULLET, // entity type
	decay, // action
	bullet_hit, // collide
	0, // interval
	0.0f, // energy
	2000.0f, // health
	1.0f, // shield
	0.0f, // length
	0.1f, // mass
	16.0f, // radius
	0, 3000, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_earth =
{
	ENTITY_TYPE_EARTH, // entity type
	gravity, // action
	planet_hit, // collide
	0, // interval
	0.0f, // energy
	1.0f, // health
	0.0f, // shield
	0.0f, // length
	10000.0f, // mass
	256.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_gun =
{
	ENTITY_TYPE_GUN, // entity type
	gun_shoot, // action
	NULL, // collide
	150, // interval
	1000.0f, // energy
	1.0f, // health
	0.0f, // shield
	0.0f, // length
	0.0f, // mass
	0.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_jupiter =
{
	ENTITY_TYPE_JUPITER, // entity type
	gravity, // action
	planet_hit, // collide
	0, // interval
	0.0f, // energy
	1.0f, // health
	0.0f, // shield
	0.0f, // length
	10000.0f, // mass
	512.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_mars =
{
	ENTITY_TYPE_MARS, // entity type
	gravity, // action
	planet_hit, // collide
	0, // interval
	0.0f, // energy
	1.0f, // health
	0.0f, // shield
	0.0f, // length
	10000.0f, // mass
	128.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_moon =
{
	ENTITY_TYPE_MOON, // entity type
	gravity, // action
	planet_hit, // collide
	0, // interval
	0.0f, // energy
	1.0f, // health
	0.0f, // shield
	0.0f, // length
	10000.0f, // mass
	64.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_phaser =
{
	ENTITY_TYPE_PHASER, // entity type
	phaser_shoot, // action
	NULL, // collide
	0, // interval
	1000.0f, // energy
	1.0f, // health
	0.0f, // shield
	0.0f, // length
	0.0f, // mass
	0.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_ray =
{
	ENTITY_TYPE_RAY, // entity type
	ray_act, // action
	NULL, // collide
	0, // interval
	1.0f, // energy
	1.0f, // health
	0.0f, // shield
	0.0f, // length
	0.0f, // mass
	4096.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_rocket =
{
	ENTITY_TYPE_ROCKET, // entity type
	aim, // action
	NULL, // collide
	0, // interval
	1000.0f, // energy
	1.0f, // health
	1.0f, // shield
	0.0f, // length
	1.0f, // mass
	16.0f, // radius
	500, 20, // acceleration
	20, 20, // deceleration
	1.0f, // rotation
};

EntityType type_ship =
{
	ENTITY_TYPE_SHIP, // entity type
	NULL, // action
	ship_hit, // collide
	0, // interval
	1000.0f, // energy
	3000.0f, // health
	1.0f, // shield
	0.0f, // length
	1.0f, // mass
	64.0f, // radius
	2000, 2000, // acceleration
	2000, 2000, // deceleration
	10.0f, // rotation
};

EntityType type_shockwave =
{
	ENTITY_TYPE_SHOCKWAVE, // entity type
	NULL, // action
	NULL, // collide
	0, // interval
	0.0f, // energy
	0.0f, // health
	0.0f, // shield
	0.0f, // length
	0.0f, // mass
	0.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};

EntityType type_sun =
{
	ENTITY_TYPE_SUN, // entity type
	gravity, // action
	planet_hit, // collide
	0, // interval
	0.0f, // energy
	1.0f, // health
	0.0f, // shield
	0.0f, // length
	50000.0f, // mass
	1500.0f, // radius
	0, 0, // acceleration
	0, 0, // deceleration
	0.0f, // rotation
};


void templates_register()
{
	entity_type_register("bullet", &type_bullet, &format_pos);
	entity_type_register("earth", &type_earth, &format_pos);
	entity_type_register("gun", &type_gun, 0);
	entity_type_register("jupiter", &type_jupiter, &format_pos);
	entity_type_register("mars", &type_mars, &format_pos);
	entity_type_register("moon", &type_moon, &format_pos);
	entity_type_register("phaser", &type_phaser, 0);
	entity_type_register("ray", &type_ray, &format_ray);
	entity_type_register("rocket", &type_rocket, &format_ship);
	entity_type_register("ship", &type_ship, &format_ship);
	entity_type_register("shockwave", &type_shockwave, 0);
	entity_type_register("sun", &type_sun, &format_pos);
}
